version: '3.8'

services:
  proxy:
    build: ./proxy
    image: ecommerce-proxy
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis-master
      - CONSISTENCY_TYPE=${CONSISTENCY_TYPE:-dynamic}
      - NUM_REPLICAS_FOR_STRONG=${NUM_REPLICAS:-1}
    networks:
      - rede_consistencia

  redis-master:
    image: redis:7-alpine
    networks:
      - rede_consistencia

  redis-replica:
    image: redis:7-alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - rede_consistencia
    deploy:
      replicas: ${NUM_REPLICAS:-1}

  avaliacoes:
    build: ./client_runner
    image: experimento-cliente
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=avaliacoes
      - NUM_REQUESTS=${NUM_REQUESTS:-2000}
      - NODE_ID=avaliacoes-{{.Task.Slot}}
    networks:
      - rede_consistencia
    volumes:
      - ${LOG_DIR_CLIENTS:-./logs}:/app/logs
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure

  catalogo:
    build: ./client_runner
    image: experimento-cliente
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=catalogo
      - NUM_REQUESTS=${NUM_REQUESTS:-2000}
      - NODE_ID=catalogo-{{.Task.Slot}}
    networks:
      - rede_consistencia
    volumes:
      - ${LOG_DIR_CLIENTS:-./logs}:/app/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pagamentos:
    build: ./client_runner
    image: experimento-cliente
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=pagamentos
      - NUM_REQUESTS=${NUM_REQUESTS:-2000}
      - NODE_ID=pagamentos-{{.Task.Slot}}
    networks:
      - rede_consistencia
    volumes:
      - ${LOG_DIR_CLIENTS:-./logs}:/app/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pedidos:
    build: ./client_runner
    image: experimento-cliente
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=pedidos
      - NUM_REQUESTS=${NUM_REQUESTS:-2000}
      - NODE_ID=pedidos-{{.Task.Slot}}
    networks:
      - rede_consistencia
    volumes:
      - ${LOG_DIR_CLIENTS:-./logs}:/app/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  carrinho:
    build: ./client_runner
    image: experimento-cliente
    depends_on:
      - proxy
    environment:
      - SERVICE_NAME=carrinho
      - NUM_REQUESTS=${NUM_REQUESTS:-2000}
      - NODE_ID=carrinho-{{.Task.Slot}}
    networks:
      - rede_consistencia
    volumes:
      - ${LOG_DIR_CLIENTS:-./logs}:/app/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  rede_consistencia:
    driver: overlay
    attachable: true